container:
  matrix:
    image: python:3.8
    image: python:3.9
    image: python:3.10
    image: python:3.11

task:
  name: test
  script:
    name: testme1
    - echo "hi there!"
  script:
    name: testme2
    - echo "hi there2!"
